# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kEeRMMKv76rzp8JMuCaytgjFIqO1fZB_
"""

from scipy.stats import norm
import numpy as np


# set mean and standard deviation
mean = 8000
std_dev = 1000

# set size of output array
size = (1, 10)

# generating normal distribution
salaries = np.random.normal(loc=mean, scale=std_dev, size=10)  # generate 10 values
salaries = salaries.astype(int)
salaries = np.abs(salaries)

# generating cumulative distribution for each element
cdf = norm.cdf(salaries, loc=mean, scale=std_dev)
print(salaries)
print(cdf)